language: node_js

notifications:
  email: false

node_js:
- stable

before_install:
- npm install -g greenkeeper-lockfile@1

before_script:
- greenkeeper-lockfile-update

script:
- npm test
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- ./tools/continuous-deployment.travis.sh

after_script:
- greenkeeper-lockfile-upload
- node node_modules/.bin/codecov
